# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 川一土的博客视界 # 标题（页签的第一部分）
subtitle: one week contributes 2% of a year # 副标题（页签的第二部分）
description: plant your tree, now! # 描述
keywords: 前端学习,前端开发,Web开发,技术分享,学习感悟 # 关键字
author: yiTuChuan # 作者
# language: zh-Hans # 简体中文语言代码
language: zh-CN # 语言，Butterfly 主题关于该配置支持三种选项，en(默认值，英文)、zh-CN(简体中文)、zh-TW(繁体中文)
timezone: Asia/Shanghai # 时区，中国标准时间（CST），即东八区（UTC+8）

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: https://zhengzehua.top # 网站主域名
permalink: :year/:month/:day/:title/ # 定义文章的永久链接结构，可以自定义如 :category/:title/
permalink_defaults: # 为永久链接中的变量设置默认值，如 category: uncategorized
pretty_urls: # 用于配置更美观的 URL
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  # 如果设为 true，保留 URL 末尾的 'index.html'
  # 如果设为 false，移除 URL 末尾的 'index.html'
  trailing_html: true # Set to false to remove trailing '.html' from permalinks
  # 如果设为 true，保留 URL 末尾的 '.html'
  # 如果设为 false，移除 URL 末尾的 '.html'

# Directory
source_dir: source # 指定存放源文件的目录
public_dir: public # 指定生成的静态网站文件存放的目录
tag_dir: tags # 指定标签页面的目录
archive_dir: archives # 指定归档页面的目录
category_dir: categories # 指定分类页面的目录
code_dir: downloads/code # 指定代码文件的下载目录
i18n_dir: :lang # 指定国际化（i18n）文件的目录，":lang" 表示使用语言作为目录名，例如 "zh-CN", "en" 等
skip_render: # 指定不需要渲染的文件或目录，可以是一个文件、目录，或者使用通配符

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
syntax_highlighter: highlight.js
highlight:
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
# theme: landscape
theme: butterfly

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
# deploy:
#   type: ''

deploy: # 项目发布/部署配置，让 Hexo 知道将当前博客项目部署在那个位置
  type: git
  repo: https://github.com/Nasir1423/Nasir1423.github.io.git
  branch: main
